cliente/urls.py
from django.conf.urls import include, url

from cliente.views import create, index_general, eliminarFactura,editarFactura,listar,createRecibo,eliminarRecibo,editarRecibo,index_factura,index_Recibo

app_name = 'factura'

urlpatterns = [
    url(r'^$', index_general, name = 'index'),
    url(r'^factura$', index_factura, name = 'index_factura'),
    url(r'^recibo$', index_Recibo, name = 'index_recibo'),
    url(r'^createRecibo$',createRecibo, name = 'createRecibo'),
    url(r'^create$', create, name = 'create'),
    url(r'^editar/(?P<id>\d+)$', editarFactura, name='editarFactura'),
    url(r'^eliminar/(?P<id>\d+)$', eliminarFactura, name='eliminarFactura'),
    url(r'^editarRecibo/(?P<id>\d+)$', editarRecibo, name='editarRecibo'),
    url(r'^eliminarRecibo/(?P<id>\d+)$', eliminarRecibo, name='eliminarRecibo'),
   
]

tallergrupal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from cliente.views import FacturaViewSet,ReciboViewSet,TicketViewSet, UpdateTicket
from rest_framework.routers import SimpleRouter

router = SimpleRouter()
router.register(r'factura', FacturaViewSet)
router.register(r'recibo', ReciboViewSet)
router.register(r'ticket', TicketViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^ticket/update/(?P<pk>\d+)',UpdateTicket.as_view()),
    url(r'^',include(router.urls)),
]

cliente/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

# Create your models here.

class Factura (models.Model):
	numero_factura = models.CharField(max_length=16)
	AGUA = 'Agua'	
	LUZ = 'Luz'
	TELEFONO = 'Telefono'
	FACTURA_OPCIONES = (
		(AGUA, 'Agua'),
		(LUZ, 'Luz'),
		(TELEFONO, 'Telefono'),
	)
	nombre_factura = models.CharField(max_length=8,choices=FACTURA_OPCIONES,default=AGUA)
	fecha_maxima = models.DateField()
	cantidad = models.DecimalField(max_digits = 8, decimal_places = 2)
	PAGADO = 'Pagado'	
	PENDIENTE = 'Pendiente'
	ACUMULADO = 'Acumulado'
	ESTADO_OPCIONES = (
		(PAGADO, 'Pagado'),
		(PENDIENTE, 'Pendiente'),
		(ACUMULADO, 'Acumulado'),
	)
	estado_factura = models.CharField(max_length=11,choices=ESTADO_OPCIONES,default='Pagado')
	

class Recibo (models.Model):
        id = models.AutoField(primary_key = True)
        numero_recibo = models.CharField(max_length=16)
        fecha_pago = models.DateField()
        nombre_de_quien_recibe = models.CharField(max_length=30)
        AGUA = 'Agua'
        LUZ = 'Luz'
        TELEFONO = 'Telefono'
        FACTURA_OPCIONES = (
                (AGUA, 'Agua'),
                (LUZ, 'Luz'),
                (TELEFONO, 'Telefono'),
        )
        concepto_recibo = models.CharField(max_length=8,choices=FACTURA_OPCIONES,default=AGUA)
        cantidad = models.DecimalField(max_digits = 8, decimal_places = 2)

class Ticket (models.Model):
	id = models.AutoField(primary_key = True)
	fecha_emision = models.DateField()
	CIUDAD1 = 'Ciudad1'
	CIUDAD2 = 'Ciudad2'
	CIUDAD3 = 'Ciudad3'
	CIUDAD4 = 'Ciudad4'
	CIUDAD5 = 'Ciudad5'
	CIUDAD_OPCIONES = (
		(CIUDAD1, 'Ciudad1'),
		(CIUDAD2, 'Ciudad2'),
		(CIUDAD3, 'Ciudad3'),
		(CIUDAD4, 'Ciudad4'),
		(CIUDAD5, 'Ciudad5'),
	)
	origen = models.CharField(max_length=11,choices=CIUDAD_OPCIONES,default='Ciudad1')
	destino = models.CharField(max_length=11,choices=CIUDAD_OPCIONES,default='Ciudad2')
	precio = models.DecimalField(max_digits = 8, decimal_places = 2)
	adquiriente = models.CharField(max_length=10)
	puesto = models.IntegerField()








	

cliente/forms.py
from django import forms

from cliente.models import Factura, Recibo

class FacturaForm (forms.ModelForm):

    class Meta:
        model = Factura

        fields = [
            'numero_factura',
            'nombre_factura',
            'fecha_maxima',
            'cantidad',
            'estado_factura',
        ]
        labels = {
            'numero_factura': 'Numero',
            'nombre_factura': 'Empresa',
            'fecha_maxima': 'Fecha Maxima',
            'cantidad': 'Cantidad',
            'estado_factura': 'Estado',
        }
        widgets = {
            'numero_factura': forms.TextInput(),
            'nombre_factura': forms.Select(),
            'fecha_maxima': forms.DateInput(),
            'cantidad': forms.NumberInput(),
            'estado_factura': forms.Select(),
        }

class ReciboForm (forms.ModelForm):

    class Meta:
        model = Recibo

        fields = [
            'numero_recibo',
            'fecha_pago',
            'nombre_de_quien_recibe',
            'concepto_recibo',
            'cantidad',
        ]
        labels = {
            'numero_recibo': 'Numero',
            'fecha_pago': 'Fecha',
            'nombre_de_quien_recibe': 'Nombre de quien recibe',
            'concepto_recibo': 'Concepto',
            'cantidad': 'Cantidad',
        }
        widgets = {
            'numero_recibo': forms.TextInput(),
            'fecha_pago': forms.DateInput(),
            'nombre_de_quien_recibe': forms.TextInput(),
            'concepto_recibo': forms.Select(),
            'cantidad': forms.NumberInput(),
        }

        

cliente/views.py
from django.shortcuts import render
from cliente.models import Factura,Recibo, Ticket
from cliente.serializers import FacturaSerializer,ReciboSerializer, TicketSerializer
from rest_framework.viewsets import ModelViewSet,generics
from rest_framework.response import Response

# Create your views here.

class FacturaViewSet(ModelViewSet):
    queryset = Factura.objects.all()
    serializer_class = FacturaSerializer

class ReciboViewSet(ModelViewSet):
    queryset = Recibo.objects.all()
    serializer_class = ReciboSerializer

class TicketViewSet(ModelViewSet):
	queryset = Ticket.objects.all()
	serializer_class = TicketSerializer

class UpdateTicket(generics.RetrieveUpdateAPIView):
	queryset = Ticket.objects.all()
	serializer_class = TicketSerializer

	def update(self, request, *args, **kwargs):
        	instance = self.get_object()
        	instance.fecha_emision = request.data.get("fecha_emision")
		instance.origen = request.data.get("origen")
		instance.destino = request.data.get("destino")
		instance.precio = request.data.get("precio")
		instance.adquiriente = request.data.get("adquiriente")
		instance.puesto = request.data.get("puesto")
        	instance.save()

        	serializer = self.get_serializer(instance,data=request.data)
        	serializer.is_valid(raise_exception=False)
        	self.perform_update(serializer)

        	return Response(serializer.data)

templates/base/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
</head>
<body>
{% block header %}

{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}


</body>
</html>

templates/facturas/factura_editar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Factura Editar</title>
</head>
<body>
    <form class="form-vertical" method="post" action="{% url 'factura:actualizarFactura' %}">
        {% csrf_token %}
        <h1>Editar Factura.</h1>
        <p>
             <label for="id_numero_factura">Numero:</label>
             <textarea rows="1" name="serie" maxlength="50" placeholder="serie">{{factura.numero_factura}}</textarea>
        </p>
        <p>
             <label for="id_nombre_factura">Nombre:</label>
              <textarea rows="1" name="serie" maxlength="50" placeholder="serie">{{factura.nombre_factura}}</textarea>
        </p>
        <input>
             <label for="id_fecha_maxima">Fecha Maxima:</label>
              <textarea rows="1" name="serie" maxlength="50" placeholder="serie">{{factura.fecha_maxima}}</textarea>
        </p>
        <p>
             <label for="id_cantidad">Total:</label>
              <textarea rows="1" name="serie" maxlength="50" placeholder="serie">{{factura.cantidad}}</textarea>
        </p>
        <p>
             <label for="id_estado_factura">Estado:</label>
              <textarea rows="1" name="serie" maxlength="50" placeholder="serie">{{factura.estado_factura}}</textarea>
        </p>
        <button type="submit">Guardar</button>

    </form>

</body>
</html>

templates/facturas/factura_eliminar.html
{% extends 'base/base.html' %}


{% block content %}
<form method="POST">
	{% csrf_token %}
	<h3>¿Desea eliminar esta factura {{facturas.numero_factura}}?</h3>
	<button type="submit">Si, eliminar</button>
    <a href="{% url 'factura:index_factura' %}">Cancelar</a>
</form>
{% endblock %}

templates/facturas/factura_formulario.html
{% extends 'base/base.html' %}


{% block header %}
	<h1>Crear Factura.</h1>
{% endblock %}

{% block content %}
<form method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Guardar</button>
</form>
{% endblock %}

templates/facturas/factura_lista.html
{% extends 'base/base.html' %}
{% load staticfiles %}



<link href="{% static 'fuentes/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


<link href="{% static 'fuentes/metisMenu/metisMenu.min.css' %}" rel="stylesheet">


<link href="{% static 'dist/css/sb-admin-2.css' %}" rel="stylesheet">

{% block header %}
	<h1>Lista de Facturas.</h1>
{% endblock %}

{% block content %}

<div class="panel-body">
                            <table class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline collapsed" width="100%">
                                    <thead class="thead-inverse">
                                    <tr>
                                      <th class="text-center sorting">Serie</th>
                                      <th class="text-center sorting">Empresa</th>
                                      <th class="text-center sorting">Fecha de vencimiento</th>
                                      <th class="text-center sorting">Total</th>
                                      <th class="text-center sorting">Estado</th>
                                      <th class="text-center">Editar</th>
                                        <th class="text-center">Eliminar</th>

                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% if facturas %}
                                        {% for factura in facturas %}
                                                <tr style="text-align: center;">
                                                    <td>{{ factura.numero_factura}}</td>
                                                    <td>{{ factura.nombre_factura }}</td>
                                                    <td >{{ factura.fecha_maxima }}</td>
                                                    <td >${{ factura.cantidad }}</td>
                                                    <td >{{ factura.estado_factura }}</td>
                                                    <!-- Editar diagnostico-->
                                                    <td >
                                                        <form action="{% url 'factura:editarFactura' factura.id %} " method="GET" style="display: inline;">
                                                            {% csrf_token %}
                                                            <input type="hidden" name="factura_id" value="{{ factura.id }}" />
                                                            <button type="submit">Editar</button>
                                                        </form>
                                                    </td>
                                                    <td >
                                                        <!-- Eliminar Factura-->
                                                        <form action="{% url 'factura:eliminarFactura' factura.id %} " method="GET" style="display: inline;">
                                                            {% csrf_token %}
                                                            <input type="hidden" name="factura_id" value="{{ factura.id }}" />
                                                            <button type="submit">Eliminar</button>
                                                        </form>
                                                    </td>
                                                </tr>

                                        {% endfor %}
										{% else %}
											<h4>No existen facturas que mostrar</h4>
										{% endif %}
</div>
<form action="/create" method="GET">
		<input type="submit" value="Crear nueva factura" />
</form>


</tbody>

{% endblock %}

templates/facturas/factura_listaPendiente.html
{% extends 'base/base.html' %}
{% load staticfiles %}



<link href="{% static 'fuentes/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


<link href="{% static 'fuentes/metisMenu/metisMenu.min.css' %}" rel="stylesheet">


<link href="{% static 'dist/css/sb-admin-2.css' %}" rel="stylesheet">

{% block header %}
	<h1>Lista de Facturas.</h1>
{% endblock %}

{% block content %}

<div class="panel-body">
                            <table class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline collapsed" width="100%">
                                    <thead class="thead-inverse">
                                    <tr>
                                      <th class="text-center sorting">Serie</th>
                                      <th class="text-center sorting">Empresa</th>
                                      <th class="text-center sorting">Fecha de vencimiento</th>
                                      <th class="text-center sorting">Total</th>
                                      <th class="text-center sorting">Estado</th>
                                      <th class="text-center">Editar</th>
                                        <th class="text-center">Eliminar</th>

                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% if facturas %}
                                        {% for factura in facturas %}
                                                <tr style="text-align: center;">
                                                    <td>{{ factura.numero_factura}}</td>
                                                    <td>{{ factura.nombre_factura }}</td>
                                                    <td >{{ factura.fecha_maxima }}</td>
                                                    <td >${{ factura.cantidad }}</td>
                                                    <td >{{ factura.estado_factura }}</td>
                                                    <!-- Editar diagnostico-->
                                                    <td >
                                                        <form action="{% url 'factura:editarFactura' factura.id %} " method="GET" style="display: inline;">
                                                            {% csrf_token %}
                                                            <input type="hidden" name="factura_id" value="{{ factura.id }}" />
                                                            <button type="submit">Editar</button>
                                                        </form>
                                                    </td>
                                                    <td >
                                                        <!-- Eliminar Factura-->
                                                        <form action="{% url 'factura:eliminarFactura' factura.id %} " method="GET" style="display: inline;">
                                                            {% csrf_token %}
                                                            <input type="hidden" name="factura_id" value="{{ factura.id }}" />
                                                            <button type="submit">Eliminar</button>
                                                        </form>
                                                    </td>
                                                </tr>

                                        {% endfor %}
										{% else %}
											<h4>No existen facturas que mostrar</h4>
										{% endif %}
</div>
<form action="/create" method="GET">
		<input type="submit" value="Crear nueva factura" />
</form>


</tbody>

{% endblock %}

templates/index.html
{% extends 'base/base.html' %}
{% block content %}

<form action="{% url 'factura:index_factura' %} " method="GET" style="display: inline;">
	<button type="submit">Factura</button>
	
</form>

<form action="{% url 'factura:index_recibo' %} " method="GET" style="display: inline;">
	<button type="submit">Recibo</button>
	
</form>

{% endblock %}

templates/recibos/lista_recibo.html
{% extends 'base/base.html' %}
{% load staticfiles %}



<link href="{% static 'fuentes/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


<link href="{% static 'fuentes/metisMenu/metisMenu.min.css' %}" rel="stylesheet">


<link href="{% static 'dist/css/sb-admin-2.css' %}" rel="stylesheet">

{% block header %}
	<h1>Lista de Recibos.</h1>
{% endblock %}

{% block content %}

<div class="panel-body">
                            <table class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline collapsed" width="100%">
                                    <thead class="thead-inverse">
                                    <tr>
                                      <th class="text-center sorting">Número  del  recibo</th>
                                      <th class="text-center sorting">Fecha  de  pago</th>
                                      <th class="text-center sorting">Nombre  de  quien  se  recibe  </th>
                                      <th class="text-center sorting">Concepto  del  recibo</th>
                                      <th class="text-center sorting">Cantidad</th>
                                      <th class="text-center">Editar</th>
                                        <th class="text-center">Eliminar</th>

                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% if recibos %}
                                        {% for recibo in recibos %}
                                                <tr style="text-align: center;">
                                                    <td>{{ recibo.numero_recibo}}</td>
                                                    <td>{{ recibo.fecha_pago }}</td>
                                                    <td >{{ recibo.nombre_de_quien_recibe }}</td>
                                                    <td >${{ recibo.concepto_recibo }}</td>
                                                    <td >{{ recibo.cantidad }}</td>
                                                    <!-- Editar diagnostico-->
                                                    <td >
                                                        <form action="{% url 'factura:editarRecibo' recibo.id %} " method="GET" style="display: inline;">
                                                            {% csrf_token %}
                                                            <input type="hidden" name="" value="{{ recibo.id }}" />
                                                            <button type="submit">Editar</button>
                                                        </form>
                                                    </td>
                                                    <td >
                                                        <!-- Eliminar Factura-->
                                                        <form action="{% url 'factura:eliminarRecibo' recibo.id %} " method="GET" style="display: inline;">
                                                            {% csrf_token %}
                                                            <input type="hidden" name="factura_id" value="{{ recibo.id }}" />
                                                            <button type="submit">Eliminar</button>
                                                        </form>
                                                    </td>
                                                </tr>

                                        {% endfor %}
										{% else %}
											<h4>No existen recibos que mostrar</h4>
										{% endif %}
</div>
<form action="/createRecibo" method="GET">
		<input type="submit" value="Crear nuevo recibo" />
</form>


</tbody>

{% endblock %}

templates/recibos/recibo_editar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Recibo Editar</title>
</head>
<body>
    <h1>Editar Recibo</h1>
    <form class="form-vertical" method="post">
        {% csrf_token %}
	    {{ form.as_p }}
        <button type="submit">Guardar</button>

    </form>

</body>
</html>

templates/recibos/recibo_eliminar.html
{% extends 'base/base.html' %}


{% block content %}
<form method="POST">
	{% csrf_token %}
	<h3>¿Desea eliminar este recibo {{recibos.numero_recibo}}?</h3>
	<button type="submit">Si, eliminar</button>
    <a href="{% url 'factura:index_recibo' %}">Cancelar</a>
</form>
{% endblock %}

templates/recibos/recibo_formulario.html
{% extends 'base/base.html' %}


{% block header %}
	<h1>Crear Recibo.</h1>
{% endblock %}

{% block content %}
<form method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Guardar</button>
</form>
{% endblock %}

templates/recibos/recibo_lista.html
{% extends 'base/base.html' %}
{% load staticfiles %}



<link href="{% static 'fuentes/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


<link href="{% static 'fuentes/metisMenu/metisMenu.min.css' %}" rel="stylesheet">


<link href="{% static 'dist/css/sb-admin-2.css' %}" rel="stylesheet">

{% block header %}
	<h1>Lista de Facturas.</h1>
{% endblock %}

{% block content %}

<div class="panel-body">
                            <table class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline collapsed" width="100%">
                                    <thead class="thead-inverse">
                                    <tr>
                                      <th class="text-center sorting">Serie</th>
                                      <th class="text-center sorting">Empresa</th>
                                      <th class="text-center sorting">Fecha de vencimiento</th>
                                      <th class="text-center sorting">Total</th>
                                      <th class="text-center sorting">Estado</th>
                                      <th class="text-center">Editar</th>
                                        <th class="text-center">Eliminar</th>

                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% if facturas %}
                                        {% for factura in facturas %}
                                                <tr style="text-align: center;">
                                                    <td>{{ factura.numero_factura}}</td>
                                                    <td>{{ factura.nombre_factura }}</td>
                                                    <td >{{ factura.fecha_maxima }}</td>
                                                    <td >${{ factura.cantidad }}</td>
                                                    <td >{{ factura.estado_factura }}</td>
                                                    <!-- Editar diagnostico-->
                                                    <td >
                                                        <form action="{% url 'factura:editarFactura' factura.id %} " method="GET" style="display: inline;">
                                                            {% csrf_token %}
                                                            <input type="hidden" name="factura_id" value="{{ factura.id }}" />
                                                            <button type="submit">Editar</button>
                                                        </form>
                                                    </td>
                                                    <td >
                                                        <!-- Eliminar Factura-->
                                                        <form action="{% url 'factura:eliminarFactura' factura.id %} " method="GET" style="display: inline;">
                                                            {% csrf_token %}
                                                            <input type="hidden" name="factura_id" value="{{ factura.id }}" />
                                                            <button type="submit">Eliminar</button>
                                                        </form>
                                                    </td>
                                                </tr>

                                        {% endfor %}
										{% else %}
											<h4>No existen facturas que mostrar</h4>
										{% endif %}
</div>
<form action="/create" method="GET">
		<input type="submit" value="Crear nueva factura" />
</form>


</tbody>

{% endblock %}

templates/recibos/recibo_listaPendiente.html
{% extends 'base/base.html' %}
{% load staticfiles %}



<link href="{% static 'fuentes/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


<link href="{% static 'fuentes/metisMenu/metisMenu.min.css' %}" rel="stylesheet">


<link href="{% static 'dist/css/sb-admin-2.css' %}" rel="stylesheet">

{% block header %}
	<h1>Lista de Facturas.</h1>
{% endblock %}

{% block content %}

<div class="panel-body">
                            <table class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline collapsed" width="100%">
                                    <thead class="thead-inverse">
                                    <tr>
                                      <th class="text-center sorting">Serie</th>
                                      <th class="text-center sorting">Empresa</th>
                                      <th class="text-center sorting">Fecha de vencimiento</th>
                                      <th class="text-center sorting">Total</th>
                                      <th class="text-center sorting">Estado</th>
                                      <th class="text-center">Editar</th>
                                        <th class="text-center">Eliminar</th>

                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% if facturas %}
                                        {% for factura in facturas %}
                                                <tr style="text-align: center;">
                                                    <td>{{ factura.numero_factura}}</td>
                                                    <td>{{ factura.nombre_factura }}</td>
                                                    <td >{{ factura.fecha_maxima }}</td>
                                                    <td >${{ factura.cantidad }}</td>
                                                    <td >{{ factura.estado_factura }}</td>
                                                    <!-- Editar diagnostico-->
                                                    <td >
                                                        <form action="{% url 'factura:editarFactura' factura.id %} " method="GET" style="display: inline;">
                                                            {% csrf_token %}
                                                            <input type="hidden" name="factura_id" value="{{ factura.id }}" />
                                                            <button type="submit">Editar</button>
                                                        </form>
                                                    </td>
                                                    <td >
                                                        <!-- Eliminar Factura-->
                                                        <form action="{% url 'factura:eliminarFactura' factura.id %} " method="GET" style="display: inline;">
                                                            {% csrf_token %}
                                                            <input type="hidden" name="factura_id" value="{{ factura.id }}" />
                                                            <button type="submit">Eliminar</button>
                                                        </form>
                                                    </td>
                                                </tr>

                                        {% endfor %}
										{% else %}
											<h4>No existen facturas que mostrar</h4>
										{% endif %}
</div>
<form action="/create" method="GET">
		<input type="submit" value="Crear nueva factura" />
</form>


</tbody>

{% endblock %}